python train_pn.py --model vgg16_pn \
    --log_dir vgg/noise_finetune\
    --pn-batch-size 1024 \
    --batch-size 128 \
    --sample_noise True \
    --data_dependent after_x \
    --sample_mean_mean 0 \
    --resume \
    --load_model  results/vgg/vgg16_pn_bsz_128_pn-bsz_1024_noise_independent_after_x_v1_mean_5e-1_std_0_1/epoch_99.pth \
    --sample_mean_var 1 \
    --sample_std_mean 0.05 \
    --sample_std_var 0 \
    --batch_renorm False \
    --lr 0.1 \
