python train_pn.py --model resnet18 \
    --log_dir resnet/oracle_resnet18_bn_bsz_128_pn-bsz_1024_noise_dependent_bsz_8 \
    --batch-size 128 \
    --pn-batch-size 1024 \
    --lr 0.1 \
    --dataset CIFAR100 \
    --r_max 0.9 \
    --noise_bsz 8 \
    --sample_noise True \
    --batch_renorm True \
    --data_dependent True \
    --project_name dual_bn_100
